version: '3.8'
services:

  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file:
      - ./mongo.env


  backend-node:
    build: ./backend
    ports:
    - '80:80'  
    volumes:
      - logs:/backend/logs
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - ./backend/backend.env
    depends_on:
      - mongodb

      
  
  frontend-node:
    build: ./frontend
    volumes:
      - ./backend/src:/backend/src
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend-node
  

volumes:
  data:
  logs:


